version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: kbsv

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_URL: mongodb://root:123456@mongo:27017/
  
  camel-etl:
    image: camel-etl:v1
    restart: always
    environment:
      KAFKA_TOPIC: vietstock_transfer_data_shareholder
      KAFKA_BROKER: 10.100.30.100:19092
      KAFKA_GROUPID: STOCK_GROUP_ID_HuyDV
      KAFKA_CLIENTID: STOCK_CLIENT_ID_HuyDV
      MONGODB_URL: mongodb://root:123456@mongo:27017
      MONGODB_COLLECTION: shareholders
      MONGODB_DATABASE: kbsv
      MONGODB_HOST: mongo:27017
      MONGODB_AUTHSOURCE: admin
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: '123456'
